"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {supabase} from "@/lib/supabaseClient";
import ForumLikeButton,{useForumLikes} from "@/app/components/ForumLikes";
import OwnerBadge from "@/app/components/OwnerBadge";
import TaskTimeFields from "@/app/components/TaskTimeFields";
import {ANY_TIME,formatTaskTime,localTimezone,timePayload,TimeRange} from "@/lib/taskTime";
import CommunityImagePicker from "@/app/components/CommunityImagePicker";
import PostImageGallery from "@/app/components/PostImageGallery";
import {POST_IMAGES_BUCKET,uploadPostImages,AVATARS_BUCKET,publicStorageUrl} from "@/lib/media";
type Kind="discussion"|"social";
type Person={id:string;username:string|null;avatar_path:string|null};
type Post={image_paths?:string[];id:string;author_id:string;kind:Kind;category:string;title:string;body:string;location:string|null;event_time:string|null;created_at:string;score:number;comment_count:number;task_schedule_v2?:boolean;task_date_from?:string|null;task_date_to?:string|null;task_time_from?:string|null;task_time_to?:string|null;task_timezone?:string|null;participants:Person[];joined:boolean};
const scheduleColumns="task_schedule_v2,task_date_from,task_date_to,task_time_from,task_time_to,task_timezone";
function AvatarStack({people,lang}:{people:Person[];lang:"zh"|"en"}){return <div className="flex -space-x-2" aria-label={lang==="zh"?"参与者头像":"Participant avatars"}>{people.slice(0,4).map(person=>{const src=publicStorageUrl(AVATARS_BUCKET,person.avatar_path);return src?<img key={person.id} src={src} alt="" title={person.username??undefined} className="h-8 w-8 rounded-full border-2 border-[#11131e] object-cover"/>:<span key={person.id} title={person.username??undefined} className="flex h-8 w-8 items-center justify-center rounded-full border-2 border-[#11131e] bg-violet-500/25 text-xs text-violet-200">{(person.username||"U")[0].toUpperCase()}</span>})}</div>}
export default function CommunityBoard({lang,kind}:{lang:"zh"|"en";kind:Kind}){
 const social=kind==="social",[rows,setRows]=useState<Post[]>([]),[uid,setUid]=useState<string|null>(null),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[msg,setMsg]=useState("");
 const [files,setFiles]=useState<File[]>([]);
 const [title,setTitle]=useState(""),[body,setBody]=useState(""),[category,setCategory]=useState(social?"activity":"service"),[location,setLocation]=useState(""),[taskTime,setTaskTime]=useState<TimeRange>({...ANY_TIME,timezone:localTimezone()});
 const copy=useMemo(()=>social?{title:lang==="zh"?"社交广场":"Social",sub:lang==="zh"?"免费活动、兴趣搭子和轻松组队":"Free activities, interests and people",button:lang==="zh"?"发布活动":"Create activity"}:{title:lang==="zh"?"讨论论坛":"Discussions",sub:lang==="zh"?"交流服务体验、观点和网站建议":"Share service experiences, ideas and feedback",button:lang==="zh"?"发布帖子":"Create post"},[lang,social]);
 const likes=useForumLikes(social?[]:rows.map(row=>row.id),uid,setMsg);
 async function load(){
  const columns=`id,author_id,kind,category,title,body,location,event_time,created_at,score,comment_count${!social?",image_paths":""}${social?","+scheduleColumns:""}`;
  const {data,error}=await supabase.from("community_posts").select(columns).eq("kind",kind).order("created_at",{ascending:false}).limit(100);if(error){setMsg(error.message);return}
  const posts=(data??[]) as any[],postIds=posts.map(row=>row.id);let participants:any[]=[];
  if(social&&postIds.length){const result=await supabase.from("community_participants").select("post_id,user_id,created_at").in("post_id",postIds).order("created_at");if(result.error){setMsg(result.error.message);return}participants=result.data??[]}
  const personIds=[...new Set([...posts.map(row=>row.author_id),...participants.map(row=>row.user_id)].filter(Boolean))];const people=new Map<string,Person>();
  if(personIds.length){const result=await supabase.from("profiles").select("id,username,avatar_path").in("id",personIds);if(result.error){setMsg(result.error.message);return}(result.data??[]).forEach(p=>people.set(p.id,p as Person))}
  setMsg("");setRows(posts.map(row=>{const ids=participants.filter(p=>p.post_id===row.id).map(p=>p.user_id);if(!ids.includes(row.author_id))ids.unshift(row.author_id);return {...row,participants:ids.map(id=>people.get(id)).filter(Boolean),joined:!!uid&&ids.includes(uid)}}));
 }
 useEffect(()=>{supabase.auth.getSession().then(({data})=>setUid(data.session?.user?.id??null)).catch(()=>setUid(null))},[]);
 useEffect(()=>{void load()},[kind,uid]);
 async function submit(){
  if(busy)return;if(!uid)return setMsg(lang==="zh"?"请先登录。":"Please sign in.");
  if(title.trim().length<3||body.trim().length<5)return setMsg(lang==="zh"?"请完善标题和内容。":"Please complete the title and content.");
  setBusy(true);setMsg("");let paths:string[]=[];let saved=false;
  try{const id=crypto.randomUUID();const schedule=social?timePayload(taskTime):{};
   if(!social)paths=await uploadPostImages(uid,"forum-post",id,files);
   const {error}=await supabase.from("community_posts").insert({id,author_id:uid,kind,category,title:title.trim(),body:body.trim(),location:social?(location.trim()||null):null,event_time:null,is_free:social,...schedule,...(!social?{image_paths:paths}:{})});
   if(error)throw error;saved=true;setFiles([]);setTitle("");setBody("");setLocation("");setTaskTime({...ANY_TIME,timezone:localTimezone()});setOpen(false);await load();
  }catch(e:any){if(!saved&&paths.length)await supabase.storage.from(POST_IMAGES_BUCKET).remove(paths);setMsg(e?.message||"Request failed")}finally{setBusy(false)}
 }
 async function join(event:React.MouseEvent,post:Post){event.preventDefault();event.stopPropagation();if(!uid)return setMsg(lang==="zh"?"请先登录后参与活动。":"Please sign in to join.");if(post.joined)return;setBusy(true);const {error}=await supabase.rpc("join_community_activity",{p_post:post.id});setBusy(false);if(error)setMsg(error.message);else await load()}
 return <main className="min-h-screen bg-[#080a12] px-5 py-10 text-white"><div className="mx-auto max-w-6xl"><div className="flex items-end justify-between gap-4"><div><h1 className="text-3xl font-black sm:text-4xl">{copy.title}</h1><p className="mt-3 text-zinc-400">{copy.sub}</p></div><div className="flex flex-wrap items-center gap-3"><button onClick={()=>setOpen(v=>!v)} className="rounded-xl bg-violet-500 px-5 py-3 text-sm font-bold">{copy.button}</button>{!social&&<a href={`/${lang}/court`} className="rounded-xl border border-violet-400/40 bg-violet-500/10 px-5 py-3 text-sm font-bold text-violet-200">{lang==="zh"?"参与小法庭":"Community court"}</a>}</div></div>
 {open&&<section className="mt-7 rounded-2xl border border-white/10 bg-[#11131e] p-5"><div className="grid gap-4 sm:grid-cols-2"><label className="sm:col-span-2"><span className="mb-2 block text-sm text-zinc-400">{lang==="zh"?"标题":"Title"}</span><input value={title} onChange={e=>setTitle(e.target.value)} className="w-full rounded-xl border border-white/10 bg-[#090b13] px-4 py-3"/></label><label><span className="mb-2 block text-sm text-zinc-400">{lang==="zh"?"类型":"Category"}</span><select value={category} onChange={e=>setCategory(e.target.value)} className="w-full rounded-xl border border-white/10 bg-[#090b13] px-4 py-3"><option value={social?"activity":"service"}>{social?(lang==="zh"?"活动":"Activity"):(lang==="zh"?"服务讨论":"Service")}</option><option value={social?"sports":"feedback"}>{social?(lang==="zh"?"运动":"Sports"):(lang==="zh"?"网站建议":"Feedback")}</option><option value={social?"study":"experience"}>{social?(lang==="zh"?"学习":"Study"):(lang==="zh"?"经验交流":"Experience")}</option></select></label>{social&&<label><span className="mb-2 block text-sm text-zinc-400">{lang==="zh"?"地点信息或线上":"Location or online"}</span><input value={location} onChange={e=>setLocation(e.target.value)} className="w-full rounded-xl border border-white/10 bg-[#090b13] px-4 py-3"/></label>}{social&&<div className="sm:col-span-2"><TaskTimeFields value={taskTime} onChange={setTaskTime} lang={lang}/></div>}<label className="sm:col-span-2"><span className="mb-2 block text-sm text-zinc-400">{lang==="zh"?"详情":"Details"}</span><textarea value={body} onChange={e=>setBody(e.target.value)} className="min-h-32 w-full rounded-xl border border-white/10 bg-[#090b13] px-4 py-3"/></label></div>{!social&&<CommunityImagePicker files={files} onChange={setFiles} lang={lang} disabled={busy} onError={setMsg}/>}<div className="mt-4 flex items-center justify-between"><span className="text-xs text-zinc-500">{social&&(lang==="zh"?"社交板块只允许免费活动。":"Social posts must be free.")}</span><button disabled={busy} onClick={submit} className="rounded-xl bg-violet-500 px-5 py-2.5 text-sm font-bold disabled:opacity-40">{busy?(lang==="zh"?"发布中…":"Posting…"):(lang==="zh"?"发布":"Post")}</button></div></section>}
 {msg&&<p className="mt-4 text-sm text-rose-300">{msg}</p>}<div className="mt-8 grid gap-4 sm:grid-cols-2">{rows.length?rows.map(row=><article key={row.id} className="group rounded-2xl border border-white/10 bg-[#11131e] p-5 transition hover:border-violet-400/40"><div className="flex items-center justify-between gap-3"><OwnerBadge userId={row.author_id} lang={lang}/><span className="rounded-full bg-violet-500/10 px-2 py-1 text-xs text-violet-300">{row.category}</span></div><Link href={`/${lang}/community/${row.id}`} className="block"><h2 className="mt-2 text-lg font-bold group-hover:text-violet-200">{row.title}</h2>{social&&<dl className="mt-4 grid gap-2 text-sm"><div><dt className="inline text-zinc-500">{lang==="zh"?"时间：":"Time: "}</dt><dd className="inline text-zinc-300">{formatTaskTime(row,lang)}</dd></div><div><dt className="inline text-zinc-500">{lang==="zh"?"地点：":"Location: "}</dt><dd className="inline text-zinc-300">{row.location||(lang==="zh"?"待定":"TBC")}</dd></div></dl>}<p className="mt-3 line-clamp-3 text-sm leading-6 text-zinc-400">{row.body}</p></Link>{!social&&<PostImageGallery paths={row.image_paths}/>} {social?<div className="mt-5 flex items-center justify-between gap-3 border-t border-white/10 pt-4"><div className="flex items-center gap-3"><AvatarStack people={row.participants} lang={lang}/><span className="text-xs text-zinc-400">{lang==="zh"?`当前参与 ${row.participants.length} 人`:`${row.participants.length} joining`}</span></div><button disabled={busy||row.joined} onClick={event=>join(event,row)} className="rounded-lg bg-violet-500 px-4 py-2 text-sm font-bold disabled:bg-zinc-700 disabled:text-zinc-400">{row.joined?(lang==="zh"?"已参与":"Joined"):(lang==="zh"?"参与":"Join")}</button></div>:<div className="mt-5 flex items-center gap-3"><ForumLikeButton state={likes.states[row.id]} busy={likes.pending.has(row.id)} onClick={()=>void likes.toggle(row.id,lang)} lang={lang}/><Link href={`/${lang}/community/${row.id}`} className="text-xs text-zinc-500">{row.comment_count} {lang==="zh"?"条评论":"comments"}</Link></div>}</article>):<div className="text-zinc-500">{lang==="zh"?"这里还没有内容。":"Nothing here yet."}</div>}</div></div></main>;
}
