"use client";
import {useEffect,useState} from "react";
import {supabase} from "@/lib/supabaseClient";
import OwnerBadge from "@/app/components/OwnerBadge";
export default function CourtCaseView({id,lang}:{id:string;lang:"zh"|"en"}){
 const zh=lang==="zh";const [row,setRow]=useState<any>(null),[uid,setUid]=useState<string|null>(null),[admin,setAdmin]=useState(false),[evidence,setEvidence]=useState<any[]>([]),[urls,setUrls]=useState<Record<string,string>>({}),[messages,setMessages]=useState<any[]>([]),[selected,setSelected]=useState<string[]>([]),[totals,setTotals]=useState<any[]>([]),[myVote,setMyVote]=useState(""),[statement,setStatement]=useState(""),[files,setFiles]=useState<File[]>([]),[consent,setConsent]=useState(false),[reason,setReason]=useState(""),[verdict,setVerdict]=useState("neither"),[busy,setBusy]=useState(false),[error,setError]=useState(""),[loading,setLoading]=useState(true);
 async function load(){
 const session=await supabase.auth.getSession();const me=session.data.session?.user.id??null;setUid(me);
 if(!me){setRow(null);setError(zh?"请先登录。":"Please sign in.");return}
 const c=await supabase.from("court_cases").select("*").eq("id",id).maybeSingle();if(c.error)throw c.error;if(!c.data)throw Error(zh?"案件不存在":"Case not found");setRow(c.data);
 const a=await supabase.rpc("is_market_admin");setAdmin(a.data===true);
 const e=await supabase.from("court_evidence").select("*").eq("case_id",id).order("created_at");if(e.error)throw e.error;setEvidence(e.data??[]);
 const mapped:Record<string,string>={};for(const entry of e.data??[])for(const path of entry.image_paths??[]){const signed=await supabase.storage.from("court-evidence").createSignedUrl(path,600);if(signed.data)mapped[path]=signed.data.signedUrl}setUrls(mapped);
 const t=await supabase.rpc("court_vote_totals",{p_case:id});if(t.error)throw t.error;setTotals(t.data??[]);
 const v=await supabase.from("court_votes").select("choice").eq("case_id",id).eq("voter_id",me).maybeSingle();setMyVote(v.data?.choice??"");
 if([c.data.owner_id,c.data.other_id].includes(me)&&c.data.status==="collecting"&&!e.data?.some(x=>x.author_id===me)){
 const d=await supabase.from("deals").select("conversation_id").eq("id",c.data.deal_id).maybeSingle();
 if(d.data){const m=await supabase.from("messages").select("id,content,sender_id,created_at").eq("conversation_id",d.data.conversation_id).order("created_at").limit(1000);if(m.error)throw m.error;setMessages(m.data??[])}
 }else setMessages([]);
 }
 useEffect(()=>{setLoading(true);void load().catch(e=>setError(e.message)).finally(()=>setLoading(false))},[id]);
 async function run(action:()=>Promise<void>){if(busy)return;setBusy(true);setError("");try{await action();await load()}catch(e){setError(e instanceof Error?e.message:"Request failed")}finally{setBusy(false)}}
 async function rpc(name:string,args:any){const {error}=await supabase.rpc(name,args);if(error)throw error}
 async function submit(){
 if(!consent||statement.trim().length<10)throw Error(zh?"请填写至少10字的阐述，并同意公开所选证据。":"Enter at least 10 characters and consent to publishing selected evidence.");
 if(files.length>10)throw Error(zh?"最多10张图片":"Maximum 10 images");
 if(files.some(f=>!["image/jpeg","image/png","image/webp"].includes(f.type)||f.size>5242880))throw Error(zh?"仅限JPG/PNG/WebP，每张最多5MB":"JPG/PNG/WebP only, max 5 MB each");
 const paths:string[]=[];for(const file of files){
 const extension=file.type==="image/jpeg"?"jpg":file.type==="image/png"?"png":"webp";const path=`${uid}/${id}/${crypto.randomUUID()}.${extension}`;
 const upload=await supabase.storage.from("court-evidence").upload(path,file,{contentType:file.type,upsert:false});if(upload.error)throw upload.error;paths.push(path)}
 await rpc("submit_court_evidence",{p_case:id,p_statement:statement.trim(),p_paths:paths,p_messages:selected});setFiles([]);setStatement("");setSelected([]);
 }
 const participant=row&&[row.owner_id,row.other_id].includes(uid);const submitted=evidence.some(e=>e.author_id===uid);
 const label=(choice:string)=>choice==="owner"?(zh?"发布方":"Publisher"):choice==="other"?(zh?"合作方":"Partner"):(zh?"双方 / 证据不足":"Both / insufficient evidence");
 if(loading)return <p>{zh?"加载中…":"Loading…"}</p>;
 if(!row)return <p className="text-rose-300">{error}</p>;
 return <div><a href={`/${lang}/court`} className="text-violet-300">← {zh?"小法庭":"Court"}</a><h1 className="mt-5 text-3xl font-black">{row.title}</h1><p className="mt-2 text-zinc-400">{row.status==="collecting"?(zh?"双方举证中":"Collecting evidence"):row.status==="voting"?(zh?"公众投票中":"Community voting"):(zh?"已裁决，记录已归档":"Ruled and archived")}</p><div className="mt-4 flex flex-wrap gap-6"><div><p className="mb-2 text-xs text-zinc-500">{label("owner")}</p><OwnerBadge userId={row.owner_id} lang={lang}/></div><div><p className="mb-2 text-xs text-zinc-500">{label("other")}</p><OwnerBadge userId={row.other_id} lang={lang}/></div></div>{error&&<p className="my-4 text-rose-300">{error}</p>}
 <div className="mt-5 grid gap-5 md:grid-cols-2">{evidence.map(e=><section key={e.id} className="rounded-2xl border border-white/10 bg-[#11131e] p-5"><OwnerBadge userId={e.author_id} lang={lang}/><p className="whitespace-pre-wrap break-words">{e.statement}</p><div className="mt-4 grid grid-cols-2 gap-2">{(e.image_paths??[]).map((path:string)=>urls[path]?<a key={path} href={urls[path]} target="_blank" rel="noreferrer"><img src={urls[path]} alt={zh?"提交的证据":"Submitted evidence"} className="h-40 w-full rounded-xl object-contain"/></a>:<p key={path} className="text-xs text-zinc-500">{zh?"图片暂不可用，请刷新":"Image unavailable. Refresh."}</p>)}</div>{(e.message_excerpts??[]).map((m:any,i:number)=><blockquote key={i} className="mt-3 rounded-xl border border-white/10 p-3"><p className="text-xs text-zinc-500">{m.sender_id===row.owner_id?label("owner"):label("other")} · {new Date(m.created_at).toLocaleString()}</p><p className="mt-1 whitespace-pre-wrap text-sm">{m.content}</p></blockquote>)}</section>)}</div>
 {row.status==="collecting"&&participant&&!submitted&&<section className="mt-6 rounded-2xl border border-white/10 p-5"><h2 className="font-bold">{zh?"提交我的证据与阐述":"Submit evidence and statement"}</h2><p className="mt-2 text-sm text-amber-300">{zh?"双方提交后材料向登录用户公开，且不能自行修改或删除。请先遮盖电话、地址等敏感信息。只选择本案相关的聊天记录；未选择的聊天不会公开。":"Evidence becomes visible to signed-in users when voting starts and cannot be edited or deleted. Redact sensitive data. Only selected chat excerpts will be published."}</p><textarea value={statement} onChange={e=>setStatement(e.target.value)} maxLength={10000} className="mt-4 min-h-36 w-full rounded-xl border border-white/10 bg-[#11131e] p-3"/><label className="mt-3 block text-sm text-zinc-400">{zh?"照片 / 截图（最多10张，每张5MB）":"Photos / screenshots (10 max, 5 MB each)"}<input type="file" multiple accept="image/jpeg,image/png,image/webp" onChange={e=>setFiles(Array.from(e.target.files??[]))} className="mt-2 block"/><span>{files.length}/10</span></label><details className="mt-4"><summary className="cursor-pointer text-violet-300">{zh?"选择站内聊天记录（最多50条）":"Select in-site chat excerpts (50 max)"}</summary><div className="mt-3 max-h-72 space-y-2 overflow-auto">{messages.map(m=><label key={m.id} className="flex items-start gap-2 rounded-xl border border-white/10 p-3 text-sm"><input type="checkbox" checked={selected.includes(m.id)} onChange={e=>setSelected(prev=>e.target.checked?(prev.length<50?[...prev,m.id]:prev):prev.filter(x=>x!==m.id))}/><span className="whitespace-pre-wrap"><span className="text-xs text-zinc-500">{new Date(m.created_at).toLocaleString()} · {m.sender_id===uid?(zh?"我":"Me"):(zh?"对方":"Other")}</span><br/>{m.content}</span></label>)}</div></details><label className="mt-4 flex gap-2 text-sm"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>{zh?"我已检查隐私信息，并同意公开阐述和所选证据用于投票。":"I checked privacy and consent to publishing my statement and selected evidence for voting."}</label><button disabled={busy||!consent} onClick={()=>run(submit)} className="mt-4 rounded-xl bg-violet-500 px-5 py-3 disabled:opacity-40">{zh?"提交并锁定证据":"Submit and lock evidence"}</button></section>}
 {row.status==="collecting"&&submitted&&<p className="mt-5 text-zinc-400">{zh?"你的证据已提交，等待对方或管理员开启投票。":"Evidence submitted. Waiting for the other party or administrator to open voting."}</p>}
 {row.status!=="collecting"&&<section className="mt-6 rounded-2xl border border-white/10 p-5"><h2 className="font-bold">{zh?"投票（仅供最终裁决参考）":"Votes (advisory only)"}</h2><div className="mt-4 flex flex-wrap gap-3">{["owner","other","neither"].map(choice=><button key={choice} disabled={busy||participant||!!myVote||row.status!=="voting"} onClick={()=>run(()=>rpc("cast_court_vote",{p_case:id,p_choice:choice}))} className="rounded-xl border border-white/10 px-4 py-3 disabled:opacity-50">{label(choice)} · {totals.find(t=>t.choice===choice)?.total??0}</button>)}</div><p className="mt-3 text-xs text-zinc-500">{myVote?(zh?"已投票":"Vote recorded"):participant?(zh?"本案双方不能投票":"Parties cannot vote on their own case"):(zh?"每个已验证邮箱账号每案一票，提交后不可更改。":"One immutable vote per verified account per case.")}</p></section>}
 {row.status==="closed"&&<section className="mt-6 rounded-2xl border border-emerald-500/30 p-5"><h2 className="font-bold">{zh?"最终裁决":"Final ruling"}：{label(row.verdict)}</h2><p className="mt-3 whitespace-pre-wrap">{row.verdict_reason}</p><p className="mt-2 text-xs text-zinc-500">{new Date(row.resolved_at).toLocaleString()}</p></section>}
 {admin&&row.status!=="closed"&&<section className="mt-6 rounded-2xl border border-rose-500/30 p-5"><h2 className="font-bold">{zh?"管理员裁决":"Administrator ruling"}</h2><textarea placeholder={zh?"操作理由 / 裁决说明，裁决至少10字":"Action / verdict reason, at least 10 characters for ruling"} value={reason} onChange={e=>setReason(e.target.value)} className="mt-3 min-h-24 w-full rounded-xl border border-white/10 bg-[#11131e] p-3"/>{row.status==="collecting"&&<button disabled={busy} onClick={()=>run(()=>rpc("admin_open_court_voting",{p_case:id,p_reason:reason}))} className="mt-3 rounded-xl border border-rose-400 px-4 py-2">{zh?"提前开启投票（对方未提交）":"Open voting early"}</button>}<select value={verdict} onChange={e=>setVerdict(e.target.value)} className="mt-3 block rounded-xl bg-[#11131e] p-3">{["owner","other","neither"].map(v=><option key={v} value={v}>{label(v)}</option>)}</select><p className="mt-3 text-xs text-zinc-500">{zh?"最终裁决会结束案件和交易，保留记录；不会自动扣款、退款或支付。":"Ruling closes the case and transaction, preserving records. No automatic payment or refund."}</p><button disabled={busy} onClick={()=>{if(window.confirm(zh?"确认最终裁决并结束交易？提交后不可撤回。":"Finalize ruling and close transaction? This cannot be undone."))void run(()=>rpc("admin_resolve_court",{p_case:id,p_verdict:verdict,p_reason:reason}))}} className="mt-3 rounded-xl bg-rose-500 px-5 py-3 disabled:opacity-40">{zh?"提交最终裁决":"Finalize ruling"}</button></section>}
 </div>
}
