"use client";
import {PlatformNotice} from "@/app/components/PlatformNotice";
import Link from "next/link";
import {useEffect,useRef,useState} from "react";

function scrollOverTime(top:number,onComplete:()=>void,duration=1400){const start=window.scrollY,target=Math.max(0,Math.min(top,document.documentElement.scrollHeight-window.innerHeight)),distance=target-start,began=performance.now();let id=0;function frame(now:number){const p=Math.min((now-began)/duration,1),eased=p<.5?4*p*p*p:1-Math.pow(-2*p+2,3)/2;window.scrollTo(0,start+distance*eased);if(p<1)id=requestAnimationFrame(frame);else onComplete()}id=requestAnimationFrame(frame);return()=>cancelAnimationFrame(id)}

export default function HomeExperience({lang}:{lang:"zh"|"en"}){
 const [scrolling,setScrolling]=useState(false);const cancelScroll=useRef<(()=>void)|null>(null);
 const [expanded,setExpanded]=useState(false),[displayedTitle,setDisplayedTitle]=useState(""),[showSubtitle,setShowSubtitle]=useState(false);const modulesRef=useRef<HTMLElement>(null);const fullTitle=lang==="zh"?"今天有什么可以帮到您？":"What can we help you with today?";
 useEffect(()=>{cancelScroll.current?.();setScrolling(false);setExpanded(false);setDisplayedTitle("");setShowSubtitle(false);window.scrollTo({top:0,behavior:"auto"});let index=0,subtitleTimer=0;const timer=window.setInterval(()=>{index++;setDisplayedTitle(fullTitle.slice(0,index));if(index>=fullTitle.length){clearInterval(timer);subtitleTimer=window.setTimeout(()=>setShowSubtitle(true),350)}},lang==="zh"?125:58);return()=>{clearInterval(timer);clearTimeout(subtitleTimer);cancelScroll.current?.()}},[fullTitle,lang]);
 const items=[["需求","Requests","发布您的需求","Post your request","demands"],["服务","Services","为他人提供服务","Offer services to others","services"],["社交","Social","免费活动与搭子","Free activities & people","social"],["讨论","Discuss","分享观点建议","Share ideas","forum"],["我的","Me","聊天与合作进度","Chats & progress","me"]];
 function toggle(){if(scrolling)return;cancelScroll.current?.();setScrolling(true);if(expanded){cancelScroll.current=scrollOverTime(0,()=>{setExpanded(false);setScrolling(false)})}else{setExpanded(true);cancelScroll.current=scrollOverTime(modulesRef.current?modulesRef.current.getBoundingClientRect().top+window.scrollY-64:window.scrollY,()=>setScrolling(false))}}
 return <main className="bg-[#080a12] text-center"><section className="relative flex min-h-[calc(100vh-4rem)] items-start justify-center overflow-hidden px-5 pt-[18vh]"><div className="pointer-events-none absolute left-1/2 top-20 h-80 w-80 -translate-x-1/2 rounded-full bg-violet-600/10 blur-3xl"/><div className="relative max-w-5xl"><h1 className="min-h-[1.2em] text-4xl font-black tracking-tight text-white sm:text-6xl">{displayedTitle}<span className={displayedTitle.length<fullTitle.length?"ml-1 inline-block h-[.9em] w-[2px] animate-pulse bg-violet-400":"hidden"}/></h1><p className={`mx-auto mt-7 text-base text-zinc-400 transition duration-700 sm:text-lg ${showSubtitle?"translate-y-0 opacity-100":"translate-y-3 opacity-0"}`}>{lang==="zh"?"请把您的需求发出来。您也可以为他人提供服务。":"Share what you need. You can also offer your services to others."}</p><div className={`transition duration-700 ${showSubtitle?"opacity-100":"opacity-0"}`}><PlatformNotice lang={lang}/></div></div></section>
 <section ref={modulesRef} className="flex min-h-[75vh] items-center px-5 pb-20 pt-28"><div className={`mx-auto grid w-full max-w-6xl grid-cols-2 gap-3 transition-all duration-[1200ms] ease-out sm:grid-cols-5 ${expanded?"translate-y-0 opacity-100":"translate-y-28 opacity-0"}`}>{items.map(([zh,en,zs,es,path],i)=><Link key={path} href={`/${lang}/${path}`} style={{transitionDelay:expanded?`${i*170}ms`:"0ms"}} className="group rounded-2xl border border-white/10 bg-[#121522] p-5 text-left transition-all duration-[950ms] hover:-translate-y-1 hover:border-violet-400/50"><div className="text-lg font-bold">{lang==="zh"?zh:en}</div><div className="mt-2 text-xs text-zinc-500">{lang==="zh"?zs:es}</div><div className="mt-5 text-violet-400">→</div></Link>)}</div></section>
 <button type="button" onClick={toggle} disabled={scrolling||!showSubtitle} aria-hidden={scrolling||!showSubtitle} className={`fixed left-1/2 z-30 flex -translate-x-1/2 flex-col items-center gap-3 text-violet-300 transition-all duration-700 ${expanded?"top-24":"bottom-9"} ${scrolling||!showSubtitle?"invisible pointer-events-none opacity-0":"opacity-100"}`}><span className="text-xs text-zinc-500">{expanded?(lang==="zh"?"回到首页":"Back to home"):(lang==="zh"?"向下探索":"Explore")}</span><span aria-hidden className={`block h-5 w-5 border-b-2 border-r-2 border-violet-400 transition-transform duration-700 ${expanded?"rotate-[225deg]":"rotate-45"}`}/></button></main>;
}
