"use client";
import {useEffect,useState} from "react";
import {supabase} from "@/lib/supabaseClient";
export default function StudentReviewAdmin({lang}:{lang:"zh"|"en"}){
 const zh=lang==="zh",[rows,setRows]=useState<any[]>([]),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[image,setImage]=useState(""),[allowed,setAllowed]=useState(false);
 async function load(){const permission=await supabase.rpc("is_market_admin");if(permission.error||permission.data!==true){setMessage(zh?"无管理员权限":"Administrator access required");return}setAllowed(true);const r=await supabase.from("student_verifications").select("id,user_id,school,file_path,status,submitted_at,reviewed_at,expires_at,reason").order("submitted_at",{ascending:false}).limit(200);if(r.error)setMessage(r.error.message);else setRows(r.data??[])}
 useEffect(()=>{void load()},[]);
 async function view(row:any){setImage("");const r=await supabase.storage.from("student-verification").createSignedUrl(row.file_path,60);if(r.error)setMessage(r.error.message);else setImage(r.data.signedUrl)}
 async function review(row:any,approve:boolean){setMessage(zh?"学生认证暂未开放":"Student verification is not available")}
 async function remove(row:any){if(!window.confirm(zh?"原图将永久删除，认证结果仍保留。确认？":"Permanently delete the original image? Verification result remains."))return;setBusy(true);const r=await supabase.storage.from("student-verification").remove([row.file_path]);setBusy(false);setImage("");setMessage(r.error?r.error.message:(zh?"已清理原图；此操作不可恢复。":"Original image removed; this cannot be undone."))}
 return <section className="mt-6 rounded-2xl border border-white/10 p-5"><h2 className="text-xl font-bold">{zh?"学生认证人工审核":"Student verification review"}</h2><span className="mt-3 inline-block rounded-full bg-amber-500/10 px-3 py-1 text-xs text-amber-300">{zh?"页面预览 · 未开通":"Page preview · Not available"}</span><p className="mt-2 text-xs text-zinc-500">{zh?"仅加载最新200条。核对学校、有效期及资料一致性；平台审核不是学校背书。每周清理审核结束7天后的原图。":"Latest 200 applications. Check university, validity and consistency; this is not university endorsement. Remove originals seven days after review every week."}</p><button onClick={load} disabled={busy} className="mt-3 text-violet-300">{zh?"刷新":"Refresh"}</button><button disabled={busy} onClick={async()=>{setBusy(true);const r=await supabase.rpc("cleanup_student_review_records");setBusy(false);setMessage(r.error?r.error.message:(zh?"已清理到期审核记录：":"Expired review records cleared: ")+r.data);await load()}} className="ml-4 text-sm text-violet-300">{zh?"清理到期审核记录":"Clean expired review records"}</button>{message&&<p role="status" className="my-3 text-sm text-amber-300">{message}</p>}{image&&<div className="my-4"><button onClick={()=>setImage("")} className="mb-2 text-sm text-violet-300">{zh?"关闭材料":"Close document"}</button><img src={image} alt={zh?"私有审核材料":"Private review document"} className="max-h-[600px] max-w-full rounded-xl object-contain"/><p className="text-xs text-zinc-500">{zh?"链接60秒有效，请勿转发或下载到私人设备。":"Link valid for 60 seconds. Do not share or save to personal devices."}</p></div>}{allowed&&<div className="mt-4 space-y-3">{rows.map(row=>{const cleanup=row.status!=="pending"&&row.reviewed_at&&Date.parse(row.reviewed_at)<=Date.now()-7*86400000;return <div key={row.id} className="rounded-xl border border-white/10 p-4"><p className="font-semibold">{row.school}</p><p className="mt-1 break-all text-xs text-zinc-500">{row.user_id} · {new Date(row.submitted_at).toLocaleString()}</p><p className="mt-2 text-sm">{row.status==="pending"?(zh?"待审核":"Pending"):row.status==="approved"?(zh?"已通过":"Approved"):(zh?"未通过":"Rejected")}{row.expires_at?" · "+new Date(row.expires_at).toLocaleDateString():""}</p>{row.reason&&<p className="mt-1 text-xs text-zinc-400">{row.reason}</p>}<div className="mt-3 flex flex-wrap gap-3 text-sm">{!cleanup&&<button disabled={busy} onClick={()=>view(row)} className="text-violet-300">{zh?"查看私有材料":"View private document"}</button>}{row.status==="pending"&&<><button disabled={true} onClick={()=>review(row,true)} className="text-emerald-300">{zh?"通过":"Approve"}</button><button disabled={true} onClick={()=>review(row,false)} className="text-rose-300">{zh?"退回补充":"Reject / resubmit"}</button></>}{cleanup&&<button disabled={busy} onClick={()=>remove(row)} className="text-rose-300">{zh?"清理到期原图":"Delete expired original"}</button>}</div></div>})}</div>}</section>
}
