"use client";
import {useEffect,useState} from "react";import {supabase} from "@/lib/supabaseClient";
export default function WorkflowPanel({userId,lang,mode}:{userId:string|null;lang:"zh"|"en";mode:string}){
 const [rows,setRows]=useState<any[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{let alive=true;setLoading(true);setError("");setRows([]);async function load(){if(!userId){setLoading(false);return}const {data,error}=await supabase.from("conversations").select("id,post_type,post_id,owner_id,other_id,last_message_text,created_at").or(`owner_id.eq.${userId},other_id.eq.${userId}`).order("created_at",{ascending:false});if(error)throw error;const result=await Promise.all((data??[]).map(async c=>{const [d,p]=await Promise.all([supabase.from("deals").select("status,workflow_status").eq("conversation_id",c.id).maybeSingle(),supabase.from(c.post_type==="service"?"services":"demands").select("title").eq("id",c.post_id).maybeSingle()]);if(d.error)throw d.error;if(p.error)throw p.error;return {...c,title:p.data?.title??c.post_id,state:d.data?.status==="done"?"done":d.data?.workflow_status??"chatting"}}));if(alive)setRows(result.filter(r=>mode==="ongoing"?r.state==="active":mode==="settling"?["settling","completion_pending"].includes(r.state):mode==="completed"?r.state==="done":r.state==="arbitration"))}load().catch(e=>{if(alive)setError(e.message)}).finally(()=>{if(alive)setLoading(false)});return()=>{alive=false}},[userId,mode]);
 const card=(r:any)=><a key={r.id} href={`/${lang}/transactions/${r.id}`} className="block rounded-xl border border-zinc-800 p-4 hover:border-violet-400"><div className="font-semibold">{r.title}</div><p className="mt-2 text-sm text-zinc-400">{r.last_message_text}</p></a>;
 if(loading)return <section className="mt-6 rounded-2xl border border-zinc-800 bg-zinc-900/30 p-5 text-zinc-400">{lang==="zh"?"加载中…":"Loading…"}</section>;if(error)return <section className="mt-6 rounded-2xl border border-zinc-800 p-5 text-rose-300">{error}</section>;
 if(mode==="completed"){const mine=rows.filter(r=>r.owner_id===userId),theirs=rows.filter(r=>r.owner_id!==userId);return <div className="mt-6 grid gap-6 md:grid-cols-2">{[[lang==="zh"?"我发布的":"Posted by me",mine],[lang==="zh"?"他发布的":"Posted by them",theirs]].map(([label,list]:any)=><section key={label} className="rounded-2xl border border-zinc-800 bg-zinc-900/30 p-5"><h2 className="text-lg font-semibold">{label}（{list.length}）</h2><div className="mt-4 space-y-3">{list.length?list.map(card):<p className="text-sm text-zinc-400">{lang==="zh"?"暂无记录。":"No records."}</p>}</div></section>)}</div>}
 return <section className="mt-6 rounded-2xl border border-zinc-800 bg-zinc-900/30 p-5">{rows.length?<div className="space-y-3">{rows.map(card)}</div>:<p className="text-zinc-400">{lang==="zh"?"暂无对应的交易记录。":"No transactions in this category."}</p>}</section>
}
