import {safeLang} from "@/lib/i18n";
import {verificationPrivacy} from "@/lib/verificationPrivacy";
export const dynamic="force-dynamic";
export default async function VerificationPrivacy({params}:{params:Promise<{lang:string}>}){
 const {lang}=await params,zh=safeLang(lang)==="zh",p=verificationPrivacy();
 const missing=zh?"尚未配置；学生证上传暂停":"Not configured; document uploads paused";
 const sections=[
 [zh?"谁负责你的资料":"Who manages your information",zh?`有求（Youqiu）用于伦敦大学社区试运营。数据控制者：${p.controller||missing}。隐私联系邮箱：3266506883@qq.com。你可以通过该邮箱申请访问、更正、删除资料或撤回可选认证。`:`Youqiu is piloting a London university community. Data controller: ${p.controller||missing}. Privacy contact: 3266506883@qq.com. Contact us to request access, correction, deletion or withdrawal of optional verification.`],
 [zh?"目的、资料范围与处理依据":"Purposes, information and legal bases",zh?"大学邮箱用于账户服务及社区准入，按提供账户服务所需处理；可选学生认证依据你的同意。我们处理邮箱、所属学校、你自愿提供的姓名和有效期、审核结果、理由、时间及到期日。上传不是使用平台的必要条件。请遮盖学号、条码、二维码、照片、生日及地址，不上传护照。":"University emails support account services and community admission, processed as necessary to provide account services. Optional student document review relies on consent. We process email, university, voluntarily supplied name and validity dates, review result, reason, timestamps and expiry. Upload is not required to use the platform. Mask student numbers, codes, photos, birth dates and addresses; do not upload passports."],
 [zh?"公开显示与共享":"Public visibility and sharing",zh?"大学认证和学生认证独立显示。大学名称默认隐藏，你可在个人资料中选择显示；隐藏时公开认证接口只返回认证状态，不返回学校名称。主动写入简介、帖子或聊天的学校信息不会自动隐藏。邮箱、证件图片、审核姓名和证件号码不会作为认证资料公开。资料不会默认提供给学校，不用于付款身份核验。依法披露或投诉处理需要另行评估适当依据。":"University and student badges are independent. University names are hidden by default; you may opt in on your profile. When hidden, the public verification API returns verification status without the school name. School information you voluntarily put in bios, posts or chats is not hidden automatically. Verification does not publish email, document images, reviewed names or document numbers. We do not automatically share documents with universities or use them for payment identity checks. Legal disclosures or complaint handling require a separate assessment."],
 [zh?"存储、访问及国际传输":"Storage, access and international transfers",zh?`Supabase 提供数据库和私有文件存储。资料仅本人及获授权管理员访问，审核链接60秒有效。部署区域：${p.region||missing}。国际传输安排：${p.transfers||missing}。管理员不得私自下载、转发证件或用作公开小法庭材料。`:`Supabase provides database and private file storage. Documents are accessible only to the applicant and authorised administrators; review links expire after 60 seconds. Deployment region: ${p.region||missing}. International transfer arrangements: ${p.transfers||missing}. Administrators must not privately download, forward or publish documents as community-court evidence.`],
 [zh?"保存和删除":"Retention and deletion",zh?`审核结束7天后停止申请人读取原图，管理员按每周清理流程永久删除原图。超过30天的待审核申请在维护时关闭；认证到期或拒绝90天后的审核记录，在原图已删除后由管理员清理。物理删除和维护不是自动完成，运营者必须履行清理流程。安全审计不记录证件号码。备份与审计保留：${p.backups||missing}。`:`Applicant access to originals stops seven days after review; administrators permanently delete originals through weekly maintenance. Pending applications older than 30 days are closed during maintenance. Review records older than 90 days after expiry or rejection are cleared after originals have been deleted. Physical deletion and maintenance are not automatic; the operator must follow the cleanup procedure. Security audit reasons must not contain document numbers. Backup and audit retention: ${p.backups||missing}.`],
 [zh?"你的选择与权利":"Your choices and rights",zh?"可以不上传学生证，大学邮箱认证不受影响。你可在个人资料撤回学生认证并申请删除原图；学生标识随后停止显示。撤回同意不影响此前合法处理。你可以联系运营者申请访问、更正、删除、限制处理，以及在适用时行使可携带和反对权；也可向英国 ICO 投诉。运营者会核对请求人身份后按适用期限答复。":"You may decline document upload without losing university email verification. Withdraw student verification and request original-image deletion from your profile; the student badge will stop displaying. Withdrawal does not affect earlier lawful processing. Contact the operator for access, correction, deletion, restriction and, where applicable, portability or objection. You may complain to the UK ICO. The operator will verify the requester and respond within applicable time limits."],
 [zh?"认证范围":"Limits of verification",zh?"认证由平台人工材料审核，不代表学校背书、完整身份核验、交易保险、押金或赔付保障。真实支付和押金系统未开通。":"Verification is manual platform document review, not university endorsement, full identity verification, insurance, deposit coverage or compensation protection. Real payments and deposits are not enabled."]
 ];
 return <main className="mx-auto max-w-3xl px-5 py-10"><h1 className="text-3xl font-bold">{zh?"认证隐私说明":"Verification privacy notice"}</h1>{<p className="mt-5 rounded-xl border border-amber-400/20 bg-amber-500/10 p-4 text-sm text-amber-300">{zh?"学生认证当前未开通，不收集新的学生证或在读证明。以下学生材料处理流程为未来规划，开放前将补齐部署等信息并更新说明。大学邮箱认证和学校显示设置仍可使用。":"Student verification is not available and no new student documents are collected. Document handling below describes future plans; deployment details and this notice must be completed before opening. University email verification and visibility preferences remain available."}</p>}<div className="mt-6 space-y-6">{sections.map(([title,body])=><section key={title}><h2 className="font-semibold">{title}</h2><p className="mt-2 whitespace-pre-wrap text-sm leading-7 text-zinc-400">{body}</p></section>)}</div></main>
}
